### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by ontech7** [ontech7/everyeye-news-bot#1]
- [x] setInterval (autopull) using `session`
- [x] Buttons instead of commands
- [x] Simulation for `everyeye.rss(...)` function (see [ontech7/everyeye-rss](https://github.com/ontech7/everyeye-rss))
- [ ] Scene and Stage for News length (and maybe autopull interval)
